# Generated by Django 5.2.10 on 2026-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_menulist_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avl_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
